name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo dkms
          version: 1.0

      - name: Build module
        working-directory: abuse-kmod
        run: sudo make install
      
      - name: Load module
        run: sudo modprobe abuse

      - name: Install abusectl
        run: sudo cargo install -p abusectl

      - name: Cat make.log
        run: sudo cat /var/lib/dkms/abuse/1.0.0/build/make.log
        if: ${{ failure() }}