name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Kernel Config (Rust)
        run: cat /boot/config-$(uname -r) | grep _RUST

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo dkms ruby
          version: 1.0

      - name: Build module
        working-directory: abuse-kmod
        run: sudo make install
      
      - name: Load module
        run: |
          sudo modprobe abuse
          ls /dev

      - name: Install abusectl
        run: sudo cargo install --path abusectl --root /usr/local

      - name: Add /dev/abuse1
        run: |
          sudo abusectl add 1 
          lsblk
          sudo abusectl remove 1
          lsblk
          sudo abusectl add 1
          lsblk

      - name: Connect /dev/abuse1 and ramdisk
        run: |
          sudo cargo build -p abuse-ramdisk --release
          sudo target/release/abuse-ramdisk 1 &> abuse.log &
          sleep 1
          lsblk

      - name: Logical test (badblocks)
        run: sudo badblocks -wsv /dev/abuse1

      - name: Performance test
        run: sudo ruby perf.rb /dev/abuse1

      - name: Error log
        run: |
          sudo cat /var/lib/dkms/abuse/1.0.0/build/make.log
        if: ${{ failure() }}

      - name: App Log
        run: |
          sudo cat abuse.log
        if: ${{ always() }}
      
      - name: kernel Log
        run: |
          sudo dmesg
        if: ${{ always() }}


        