name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Kernel version
        run: uname -a

      - name: Check Kernel Config (Rust)
        run: cat /boot/config-$(uname -r) | grep _RUST

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo dkms ruby
          version: 1.0

      - name: Build module
        working-directory: azbuse-kmod
        run: |
          mkdir -p /var/lib/dkms
          sudo make install
      
      - name: Load module
        run: |
          sudo modprobe azbuse
          ls /dev

      - name: Install azbusectl
        run: sudo cargo install --path azbusectl --root /usr/local

      - name: Add /dev/azbuse1
        run: |
          sudo azbusectl add 1 
          lsblk
          sudo azbusectl remove 1
          lsblk
          sudo azbusectl add 1
          lsblk

      - name: Connect /dev/azbuse1 and ramdisk
        run: |
          sudo cargo build -p ramdisk --release
          sudo target/release/ramdisk 1 &> azbuse.log &
          sleep 1
          lsblk

      - name: Logical test (badblocks)
        run: sudo badblocks -wsv /dev/azbuse1

      - name: Performance test
        run: sudo ruby tests/perf.rb /dev/azbuse1

      - name: Kernel module build error
        run: |
          sudo cat /var/lib/dkms/azbuse/1.0.0/build/make.log
        if: ${{ failure() }}

      - name: Application Log
        run: |
          sudo cat azbuse.log
        if: ${{ always() }}
      
      - name: dmesg
        run: |
          sudo dmesg
        if: ${{ always() }}